name:               UwUpp
version:             0.1.0.0
github:              "Deltaphish/UwUpp"
license:             BSD3
author:              "Joakim Anderlind"
maintainer:          "joakimanderlind@gmail.com"
copyright:           "2020 Joakim Anderlind"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/UwUpp#readme>

dependencies:
- base >= 4.7 && < 5
- megaparsec >= 8.0 && < 9
- text >= 1.2 && < 2
- parser-combinators >= 1.2 && < 2
- parsers >= 0.12 && < 2
- containers >= 0.6.2 && < 1
- mtl >= 2.2 && < 3.0
- optparse-applicative >= 0.15 && < 1
- split >= 0.2 && < 0.3
- llvm-hs-pure >= 8.0.0 && < 10.0.0
- bytestring >= 0.10 && < 0.11

library:
  source-dirs: src

executables:
  UwUpp-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - UwUpp
    - megaparsec

tests:
  UwUpp-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - UwUpp
